ESPACO = ' '
REGEX_IDENTIFICADOR = '[a-zA-Z]+\w*'
REGEX_FLOAT = '\d+\.\d*'
REGEX_SIMBOLOS_RESTANTES = '\>=|\<=|\:=|\<>|\>|\<|\,|\+|\-|\*|\(|\)|\:(?!\=)|\.$|\;|\/'
REGEX_PONTO_NUMERO_ESPACO = '\s\.\d+'
REGEX_PONTO_NUMERO = '^\.\d+'
REGEX_INT = '\d+'
REGEX_COMENT = '//'
